### ISSUE TITLE
zookeeper is not a recognized option

### ISSUE THREAD

**Issue by Jcodelove** [banzaicloud/koperator-docs#88]
The command is an error

```shell
kubectl -n kafka run kafka-topics -it --image=ghcr.io/banzaicloud/kafka:2.13-3.1.0 --rm=true --restart=Never -- /opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper-client.zookeeper:2181 --topic my-topic --create --partitions 1 --replication-factor 1
```
In image ghcr.io/banzaicloud/kafka:2.13-3.1: zookeeper is not a recognized option
form https://banzaicloud.com/docs/supertubes/kafka-operator/test/

**Comment by hi-im-aren** [comment]
Hi @Jcodelove I was able to reproduce the issue:
```bash
Exception in thread "main" joptsimple.UnrecognizedOptionException: zookeeper is not a recognized option
    at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
    at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
    at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
    at joptsimple.OptionParser.parse(OptionParser.java:396)
    at kafka.admin.TopicCommand$TopicCommandOptions.<init>(TopicCommand.scala:567)
    at kafka.admin.TopicCommand$.main(TopicCommand.scala:47)
    at kafka.admin.TopicCommand.main(TopicCommand.scala)
Stream closed EOF for kafka/kafka-topics (kafka-topics) 
```

You can try using the following command:
```
kubectl -n kafka run kafka-topics -it --image=ghcr.io/banzaicloud/kafka:2.13-3.1.0 --rm=true --restart=Never -- /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-all-broker.kafka:29092 --topic my-topic --create --partitions 1 --replication-factor 1
```
